language: ruby
rvm:
  - 2.4.1

before_script:
 - chmod +x ./script/cibuild # just in case

# Use Bundler
script: ./script/cibuild

# Branch whitelist
branches:
  only:
  - gh-pages # test the gh-pages branch
  - master # jekyll processing happens here

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # use travis's container infrastructure

cache: bundler # speed up builds

# Notifications about build status
notifications:
  email: true

