# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Somesh's Blog
tagline:             
description:         
url:                 https://somesh.co
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Somesh Kar
  url:               https://twitter.com/SomeshKar
  email:             i@somesh.co

# Custom vars
# version:             1.0.0
# email:             i@somesh.co

# Gems
gems: [jekyll-paginate]
